---
jobs:
  - name: job-next-pipeline
    public: true
    plan:
      - task: next-pipeline
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: echo
            args: [next pipeline]

